name: Web PR Build

on:
  pull_request:
    # paths:
    # - "100masu-trainer-aws/**"
    # - "100masu-trainer-web/**"
    # - "100masu-trainer-api/**" // TODO: Add API build

jobs:
  api-build:
    if: |
      ${{ 
        github.event_name == 'push' &&
        github.event.head_commit.modified && 
        contains(github.event.head_commit.modified, '100masu-trainer-api/') 
      }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Gradle build
        working-directory: ./100masu-trainer-api
        run: ./gradlew build

      - name: copy jar
        working-directory: ./100masu-trainer-api
        run: cp build/libs/*.jar build/libs/app.jar

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifact
          path: ./100masu-trainer-api/build/libs/app.jar

  web-build:
    if: |
      ${{ 
        github.event_name == 'push' &&
        github.event.head_commit.modified && 
        contains(github.event.head_commit.modified, '100masu-trainer-web/') 
      }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./100masu-trainer-web
        run: npm install

      - name: Run build
        working-directory: ./100masu-trainer-web
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifact
          path: ./100masu-trainer-web/dist/

  pulumi-preview:
    needs: web-build

    if: |
      ${{ 
        github.event_name == 'push' && 
        github.event.head_commit.modified && 
        (
          contains(github.event.head_commit.modified, '100masu-trainer-web/') ||
          contains(github.event.head_commit.modified, '100masu-trainer-aws/')
        ) 
      }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-artifact
          path: /

      - name: Copy distribution
        run: |
          cp -r app.jar ./100masu-trainer-aws/app/api/app.jar
          cp -r dist/ ./100masu-trainer-aws/app/web/dist/

      - name: Npm Install
        working-directory: ./100masu-trainer-aws
        run: npm install

      - name: Pulumi preview
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: ttsham6/100masu-trainer-aws/dev
          work-dir: ./100masu-trainer-aws
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
