name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - "100masu-trainer-aws/**"
      - "100masu-trainer-web/**"

jobs:
  web-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./100masu-trainer-web
        run: npm install

      - name: Run build
        working-directory: ./100masu-trainer-web
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-artifact
          path: ./100masu-trainer-web/dist/

  pulumi-up:
    needs: [web-build]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Download API artifact
        uses: actions/download-artifact@v4
        with:
          name: api-artifact
          path: ./

      - name: Download web artifact
        uses: actions/download-artifact@v4
        with:
          name: web-artifact
          path: dist/

      - name: Copy distribution
        run: |
          cp -r app.jar ./100masu-trainer-aws/app/api/app.jar
          mkdir -p ./100masu-trainer-aws/app/web/dist/
          cp -r dist/ ./100masu-trainer-aws/app/web/dist/

      - name: Npm Install
        working-directory: ./100masu-trainer-aws
        run: npm install

      - name: Pulumi preview
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: ttsham6/100masu-trainer-aws/dev
          work-dir: ./100masu-trainer-aws
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
